server:
  port: 9854

spring:
  application:
    name: Environment-Service
  profiles:
    active: native

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/