server:
  port: 9854

spring:
  application:
    name: Environment-Service
  profiles:
    active: native

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  
management:
  security:
    enabled: false

logging:
  level:
    com.medici.app.eureka.client: DEBUG