spring:
  application:
    name: Ribbon-Service

server:
  port: 8965
  ribbon: 
    ServerListRefreshInterval: 1000
    eureka:
      enabled: true

Environment-Service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9854,localhost:9888,localhost:9999
    ServerListRefreshInterval: 15000

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    appname: Ribbon-Service 
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

logging:
  level:
    com.medici.app.eureka: DEBUG