server:
  port: 8965
  ribbon: 
    ServerListRefreshInterval: 1000
    eureka:
      enabled: true

spring:
  application:
    name: Ribbon-Service

Environment-Service:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:9854,localhost:9996,localhost:9997,localhost:9998,localhost:9999
    ServerListRefreshInterval: 50000

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    appname: Ribbon-Service 
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
management:
  security:
    enabled: false