server:
  port: 9832

spring:
  application:
    name: Zuul-Service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  routes:
    gateway-Service:
      serviceId: ENVIRONMENT-SERVICE

logging:
  level:
    com.medici.app.eureka: DEBUG